pipeline:
  name: TestGitCredential
  identifier: TestGitCredential
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: etest
        identifier: etest
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: "echi "
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
