pipeline:
  name: samplepipeline
  identifier: samplepipeline
  projectIdentifier: Gitops
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "Hi"
  variables:
    - name: hello
      type: String
      description: ""
      required: true
      value: <+input>
  properties:
    ci:
      codebase:
        repoName: account.flyway_db_schema
        build: <+input>
